### ISSUE TITLE
[ w3-pandas-project] Marc Nosàs Pomares

### ISSUE THREAD

**Issue by Pomilusky** [Ironhack-Data-Madrid-Enero-2022/w3-pandas-project#1]
https://github.com/Pomilusky/data-cleaning-pandas.git

**Comment by Fominayasg** [comment]
# Buenass Marc!!! :smile:
Voy a echar un ojo a tu proyecto y te dejaré por aquí mi feedback con lo que más me ha gustado y con cosillas a mejorar.

Aunque te llegue al mail, verás mucho mejor mi comentario directamente en la issue.

## README
El readme está suuuper completo, me ha gustado mucho. Muy organizado y fácil de leer.

Hay alguna errata en algunas palabras, dake una vuelta para dejarlo niquelado y estará perfect.

GEnial que hayas aprovechado el formato markdown.

## ESTRUCTURA DEL REPO
+ Está muy bien organizado en carpetas, lo único es que por convención, los archivos de código están en la carpeta `src` y los jupyter notebooks en la carpeta `notebooks` o en la carpeta raíz.

+ Al archivo de funciones plis plis plis no le llames functions.py. Mejor ponerle un nombre que identifique qué tipo de funciones vamos a encontrar dentro, `cleaning_functions.py` por ejemplo.

+ Acuérdate de meter en el gitignore los archivos que no quieras que se suban al repositorio. En este caso se te ha escapado `__pycache__`.

+ Genial que numeres los jupyters, le hace la vida mucho más fácil al lector.

## CÓDIGO
### ANÁLISIS EXPLORATORIO

Genial que hayas explicado con texto (y además super bien desarrollado) Lo que tu interpretas de ese análisis exploratorio.

Me faltaría que explores el resto de columnas también, aunque luego no las vayas a limpiar, el orden del proceso sería primero el análisis exploratorio general de toooodo el dataset (mínimo un value counts de cada columna) y luego si quieres,  una exploración más profunda de las columnas que te llamen la atención.

Una vez que ya has observado todos los datos, entonces ya  haces tus hipótesis. Ten en cuenta que en este caso es un tema que nos es familiar y podemos intentar sacar hipótesis incluso sin ver los datos, pero es una visión sesgada y podríamos estar pasando por alto cosas importantes.

Igualmente has propuesto unas hipótesis super interesantes!!! 🦈

### LIMPIEZA

La limpieza es super precisa y bien ejecutada. Top! La limpieza del año está muy muy bien pensada.

La función `clean_columns` llama a otras funciones dentro del propio punto py!! 😍🧠

Solo tengo un par de cosillas que decir para mejorar:

Te falta comentar las últimas funciones, ayyy con lo bien que habías empezado... jejeje

Por otra parte todos estos `elifs`de la función country_clean:

```python
for country in countries:
        if '?' in country: country = country[:len(country)-1]
        if country == 'Usa' or country == 'Columbia' or 'New Britain' in country: country = 'United States'
        elif 'England' == country or 'British' in country or country == 'Scotland': country = 'United Kingdom'
        elif 'Ceylon' in country: country = 'Sri Lanka'
        elif 'Anda' in country: country = 'India'
        elif 'Red Sea' in country: country = 'Egypt'
        elif 'Reunion' in country: country = 'Madagascar' # It is the closest country to the islands, even though they are a French colony (Won't put it as French territory, colonies should be part of the past, also wouldn't a good indicator)
        elif 'Okinawa' == country: country = 'Japan'
        elif 'Arab Emirates' in country or 'Persian Gulf' in country or 'Arabian' in country: country = 'United Arab Emirates'
        elif 'Antigua' == country: country = 'Antigua and Barbuda'
        elif 'Johnston Island' == country or 'Pacific' in country or 'Pacifc' in country: country = 'Pacific Ocean'
        elif 'Azores' == country or 'Atlantic' in country or 'Caribbean' in country: country = 'Atlantic ocean'
        elif 'New Guinea' == country or 'Admiralty Islands' == country: country='Papua New Guinea'
        elif country in ['Java', 'Indian Ocean', 'Inida','Bay Of Bengal','Andaman Islands']: country = 'India'
        elif 'Federated States Of Micronesia' == country: country = 'Federated States of Micronesia'
        elif 'Burma' == country: country= 'Myanmar'
        elif '/' in country: country = country.split('/')[0].strip()
        elif country == 'Gulf Of Aden': country = 'Egypt'
        elif 'Maldi' in country: country = 'Maldives'
        elif country in ['St. Maartin','Curacao', 'Nevis','Roatan','San Domingo','Netherlands Antilles']:
            country = 'Atlantic ocean'
        elif 'Tobago' == country: country = 'Trinidad and Tobago'
        elif 'Crete' == country or 'Mediterranean Sea' == country: country = 'Greece'
        elif 'Bahrein' == country: country = 'Bahrain'
        elif 'Palestin' in country: country = 'Palestine'
        elif 'China' in country: country = 'China'
        elif 'North Sea' in country: country = 'Sweden'
        elif 'West Indies' == country: country = 'Mexico'
        elif 'Tasman Sea' == country: country = 'Australia'
        elif 'Western Samoa' == country: country = 'Samoa'
        elif 'The Balkans' == country: country = 'Albania'
        elif 'Korea' == country: country = 'South Korea'
        elif 'Cayman' in country: country = 'Cayman Islands'
        elif 'np.nan' == country: country = np.nan
        result_countries.append(country)
```
Un *dicsionarito* po favoh!! Cuando veas que tienes que meter muchisimos elifs en el código.. normalmente lo puedes soucionar con un diccionario.
Puedes ver un ejemplo [aquí](https://stackoverflow.com/questions/20250771/remap-values-in-pandas-column-with-a-dict-preserve-nans).

También puedes aplicarlo en la función `append_world`.
### VISUALIZACIÓN

Los gráficos están bien elegidos en función de lo que quieres representar, pero me falta la interpretación escrita.

Ten en cuenta que no todo el mundo tiene por qué saber interpretar gráficos, y aunque a ti te resulten muy autoexpicativos, hace falta una explicación más amplia.

Eso si... me parece brutal que te hayas enfangado tu solito con geopandas y hayas sacado ese mapita, 🐳:heart:🗺 !!!!

## CONCLUSIONES E INTERPRETACIÓN

Aunque las hayas puesto en el README me hubiera gustado leerlas al final de la visualización, más que nada por seguir el hilo completo del proyecto y no tener que volver al readme al final. 

Quizá podrías ponerlo muy resumido en el readme y más extenso en el jupyter por ejemplo. Pero esto ya es cuestión de cómo lo veas tu.



En general suuuper buen trabajo Marc!! Enhorabuena!! 
🚀🚀🚀🚀🚀🚀🚀🚀🚀
