### ISSUE TITLE
[w3-pandas-project] Pablo Mora

### ISSUE THREAD

**Issue by pablomora213** [Ironhack-Data-Madrid-Enero-2022/w3-pandas-project#2]
https://github.com/pablomora213/W3_Project_Pablo.git

Proyecto terminado!

**Comment by Fominayasg** [comment]
# Buenas Pablo!! 😄 

Vamos a ver qué tal ese proyecto!! 

Voy a echar un ojo a todo el proyecto y te dejaré por aquí mi feedback con lo que más me ha gustado y con cosillas a mejorar.

Aunque este mensaje te llegue al mail, podrás verlo mucho mejor directamente en la issue en github. 

# README
El readme está muy bien trabajado y claro, de cara a futuros proyectos no especificaría tanto que has hecho en el análisis y la limpieza(si quieren verlo que se metan en los jupyter). Pero en este concretamente que lo importante es justo eso, está bien.

En cuanto a las conclusiones cuidado con decir que `El tiburón blanco es el más agresivo porque tiene muchos mas ataque que el resto de los tiburones` ¿Puede ser que sea el tiburón más abundante? por ejemplo... Para está afirmación necesitarçias saber mas datos, el resto está perfect.

En cuanto al technology stack, no se suele poner los alias sino simplemente el nombre de la libreria linkeado con su documentación correspondiente y ya.

Genial que hayas aprovechado el formato markdown para dejar el readme organizado y claro!! 🤓

# ESTRUCTURA DEL REPO
Los `.csv` mejor en una carpeta `data`. Queda más organizado que si encontramos mil archivos de primeras en la carpeta raíz.

 Si además numeras los jupyter notebooks es mucho más fácil para el lector saber en qué orden meterse para ir siguieno el orden lógico del proyecto.

# CÓDIGO

Lo primero, ¡Has documentado todas las funciones!! 👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼
## Análisis exploratorio

Se te ha quedado un poco corto. El proceso a seguir sería primero el análisis exploratorio general de toooodo el dataset (mínimo un value counts de cada columna, un shape...) y luego si quieres,  una exploración más profunda de las columnas que te llamen la atención. 

Después formular las hipótesis, una vez que ya sabes con qué datos estás tratando.

Cuando tengas claro cual va a ser tu "camino" entonces comienzas a limpiar las columnas necesarias

## Limpieza

Cuando veas que estás usando muchos elifs en una función mira a ver si puedes usar un diccionario para simplificar el código. 

[Aquí](https://stackoverflow.com/questions/20250771/remap-values-in-pandas-column-with-a-dict-preserve-nans) tienes un ejemplo de como limpiar una columna usando un diccionario ( habrá ocasiones en las que no te quede más remedio que meter unos cuantos elifs)

He visto que en el jupyter de visualización has metido una función de limpieza:
```python
def identificacion(x):
    x=str(x).lower()
    if "oth" in x:
        return np.nan
    elif x == "nan":
        return np.nan
    else:
        return x
```

Esta función lo suyo es meterla en el archivo de funciones, aunque supongo que es algo que hiciste después y no te dió tiempo pero cuando tengas un ratillo, mejor en el archivo a parte y así no entorpece la visualización.

Las funciones están super bien pensadas, y has conseguido limpiar columnas complejas (como la de especie de tiburón) de manera eficiente y bastante sencilla, ¡enohorabuena!
## Visualización

Los plots están bien escogidos para respaldar tu hipótesis y los colores se distinguen con facilidad, queda pendiente conseguir que los colores sean los mismos para las variables en todos los diagramas y así no llevar a error, pero te quedá como next steps.

Por otro lado cuando tengas tiempo comenta más cada diagrama, es decir, explica lo que tu ves en el plot como si se lo estuvieras explicando a alguien que no entiende nada del proyecto, en cen cuenta que aunque para ti sea muy obvio lo que significan los plots, no todo el mundo tiene porque saber interpretar gráficos, parte de tu trabajo como analista será explicar esas conclusiones obtenidas de tu análisis.

# INTERPRETACIÓN Y CONCLUSIONES

Aunque lo has puesto en el readme, me encantaría ver una conclusión final en el jupyter, un poco más elaborada que en readme a poder ser, después de toda la limpieza y la visualización es como que la mente pide el cerrar con una idea que resuma todo lo que acabo de ver. Plantea tus proyectos como si fueran una historia que otra persona tiene que leer: Plantear el problema, exponer el proceso, y cerrar con una idea final.

Buen trabajo Pablo!!! Sigue así y recuerda que simepre puedes añadir lo que quieras a tus proyectos y seguir mejorandolos con lo que vas aprendiendo!!

:rocket::rocket::rocket::rocket::rocket:
