### ISSUE TITLE
[ w3-pandas-project] Rodrigo Galan

### ISSUE THREAD

**Issue by rodrigogalan** [Ironhack-Data-Madrid-Enero-2022/w3-pandas-project#3]
https://github.com/rodrigogalan/data-cleaning-pandas.git

Proyecto terminado, alguna que otra duda sobre como modificar parámetro en los gráficos de la libreria plotly.

**Comment by Fominayasg** [comment]
# Buenas Rodri!! :smile:

Lo primero de todo.... ¡¡¡😍😍😍😍😍😍la fotoooo😍😍😍😍😍!!! jajajajaja ❤️🐠

Vamos a ver qué tal ese proyecto!! 

Voy a echar un ojo a todo el proyecto y te dejaré por aquí mi feedback con lo que más me ha gustado y con cosillas a mejorar.

Aunque este mensaje te llegue al mail, podrás verlo mucho mejor directamente en la issue en github. 

# README
El README está genial, conciso y claro. Dale un último repaso para revisar erratas(has puesto suf en vez de surf por ejemplo).

Yo personalmente le daría más protagonismo a las hipótesis,poniéndo por ejemplo:

#### Hipótesis
1. El surf el deporte más peligroso en relacion a los accidentes por tiburón.
1. El número de muertes por tiburón en función del número de casos ha disminuido en los últimos años

En cuanto al technology stack, genial que lo hayas puesto linkeado a la documentación, aunque en el caso de `re` lo que has linkeado es el propio repositorio de la librería.

# ESTRUCTURA DEL REPO

Está muy bien estructurado en carpetas separando funciones e imágenes, solo te falta el `.csv` en una carpeta `data`. Queda más organizado que si encontramos mil archivos de primeras en la carpeta raíz.

En este caso solo hay dos jupyter notebooks, uno para el análisis exploratorio y otro para la visualización. Pero si los numeras ayudas al lector a seguir el proceso de tu proyecto, sé que suena tremendamente obvio pero piensa que cuanto más fácil se lo pongas a la persona que entre en tu repo más probable es que se metar a indagar.


# CÓDIGO
## Análisis exploratorio

El primer análisis exploratorio se me ha quedado un poco corto. Lo ideal sería que explores el resto de columnas también, aunque luego no las vayas a limpiar, el orden del proceso sería primero el análisis exploratorio general de toooodo el dataset (mínimo un value counts de cada columna) y luego si quieres,  una exploración más profunda de las columnas que te llamen la atención(como has hecho después en la limpieza, pero está bien mirarlas antes de formular la hipótesis aunque sea un poco).

Una vez que ya has observado bien todos los datos, entonces ya  haces tus hipótesis. Ten en cuenta que en este caso es un tema que nos es familiar y podemos intentar sacar hipótesis incluso sin ver los datos, pero es una visión sesgada y podríamos estar pasando por alto cosas importantes.

Genial que hayas comentado la información que vas sacando de la exploración.

## Limpieza

La limpieza está genial estructurada, todo compartimentado en funciones. No te imaginas lo fan que soy de esta celda!!
```python
sharks["sex"] = sharks["sex"].apply(limpieza_sex)
sharks["age"] = sharks["age"].apply(limpieza_age)
sharks["year"] = sharks["year"].apply(limpieza_year)
sharks["fatal_(y/n)"] = sharks["fatal_(y/n)"].apply(limpieza_fatal)
sharks["hour"] = sharks["time"].apply(limpieza_time)
sharks.drop(columns = ["time"],axis=1,inplace= True)
sharks["type"] = sharks["type"].apply(limpieza_type)
sharks["months_code"] = sharks["date"].apply(limpieza_meses)
sharks["day"] = sharks["date"].apply(limpieza_dias)
sharks.drop(columns = ["date"],axis=1,inplace= True)
sharks["species"] = sharks["species"].apply(limpieza_species)
sharks["injury"] = sharks["injury"].apply(limpieza_injury)
sharks["country"] = sharks["country"].apply(limpieza_country)
sharks["activity"] = sharks["activity"].apply(limpieza_activity)
```

Con ella te limpias casi todo el dataset del tirón!! 😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍😍

En cuanto a las funciones en sí, están muy bien en general, has utilizado diferentes técnicas(funciones lambda, regex...), ¡genial!. Como punto a mejorar cuando tengas un montón de elifs seguidos mira a ver si lo puedes solucionar con un diccionario. Te dejo por [aquí](https://stackoverflow.com/questions/20250771/remap-values-in-pandas-column-with-a-dict-preserve-nans) un ejemplo de limpieza usando diccionarios.

He visto que en una de las funciones importas un `.csv`de países, ¿de dónde sale? ¿lo has hecho tu? Al no estar en github ni mencionar la fuente no puedo reproducir esa limpieza. Quizá puedes sacar el link de donde lo has sacado o directamente subirlo a la carpeta `data`.

## Visualización

Cuidado con exportar las figuras en html porque github no renderiza archivos tan grandes y no los muestra. Se pueden ver usando [nbviewer](https://nbviewer.org/).

Una opción que puedes hacer es poner directamente en el jupyter notebook una celda markdown con el link de la figura que quieres mostrar en nbviewer.Algo así:

```markdown
Puedes ver la figura haciendo click [aquí](https://nbviewer.org/github/rodrigogalan/data-cleaning-pandas/blob/main/Figures/activity.html)
````
Que quedaría así:

Puedes ver la figura haciendo click [aquí](https://nbviewer.org/github/rodrigogalan/data-cleaning-pandas/blob/main/Figures/activity.html)

Otra opción (puedes dejar las dos) es exportar el plot como imagen en vez de html e insertarlo en una celda markdown(aunque no será interactiva).
Como ya he dicho antes, cuanto más fácil se lo pongas a la persona que entre en tu repo más probable es que se metar a indagar.

Además es una pena que con lo chulos que te han quedado los gráficos de plotly, luego no se vean. Sobretodo si el objetivo del jupyter notebook es justo la visualización.

# INTERPRETACIÓN Y CONCLUSIONES

Me faltan las interpretaciones de los gráficos. Es importante que expliques lo que tu ves en el plot como si se lo estuvieras explicando a alguien que no entiende nada del proyecto, ten en cuenta que aunque para ti sea muy obvio lo que significan los plots, no todo el mundo tiene porque saber interpretar gráficos, parte de tu trabajo como analista será explicar esas conclusiones obtenidas de tu análisis.

En cuanto a las conclusiones, estaría bien que al final pusieras un par de frases que dejen el proyecto cerrado. Algo así como:

"Tal y como hemos comprobado, confirmamos tal hipótesis por tal y tal y rechazamos esta otra por tal y tal"


Como valoración general del proyecto, está muy muy bien Rodrigo, se nota que has currado y has profundizado tanto en al limpieza como en la visualización. ¡Muy muy buen trabajo! ¡Enhorabuena! :rocket::rocket::rocket::rocket::rocket::rocket::rocket:
