### ISSUE TITLE
[w3-pandas-project] Marilyn Gutiérrez

### ISSUE THREAD

**Issue by Marilyn499** [Ironhack-Data-Madrid-Enero-2022/w3-pandas-project#4]
https://github.com/Marilyn499/data-cleaning-pandas

**Comment by Fominayasg** [comment]
# Buenas Marilyn!! :smile:

Vamos a ver qué tal ese proyecto!! 

Voy a echar un ojo a todo el proyecto y te dejaré por aquí mi feedback con lo que más me ha gustado y con cosillas a mejorar.

Aunque este mensaje te llegue al mail, podrás verlo mucho mejor directamente en la issue en github. 

# README

El readme está genial Marilyn!! Claro y conciso. Genial que hayas puesto los links a los propios jupyter notebooks en el readme, hace el repo mucho más fácil de seguir.

El resumen en una imagen me parece top!! Si fuera un recruiter buscando a una persona para un proyecto de BI captaría mi atención. Si te gusta el rollo más adelante currate un dashboard de tableau o powerBI.

En cuanto al apartado "fuentes", aquí sólo pondría el link a kaggles para ver de dónde has sacado los datos y luego puedes hacer un apartado "technology stack" en el que pongas solo el nombre de las herramientas que usaste para hacer el proyecto linkadas a su documentación. Puedes escribirlo así:

```markdown
#### Technology Stack

- [Folium](https://python-visualization.github.io/folium/)
- [Pandas](https://pandas.pydata.org/docs/)
- [Geopandas](https://geopandas.org/)
- [Mongodb](https://www.mongodb.com/)
```
Para que se vea asi: 

#### Technology Stack

- [Folium](https://python-visualization.github.io/folium/)
- [Pandas](https://pandas.pydata.org/docs/)
- [Geopandas](https://geopandas.org/)
- [Mongodb](https://www.mongodb.com/)

---

# ESTRUCTURA DEL REPO

La estructura está perfect. 

Como próximas mejoras en este proyecto ponte como objetivo meter las funciones en un archivo `.py` para que el código sea más legible y ordenado. Y luego metes todos tus archivos `.py`en una carpeta `src`.

# CÓDIGO

## Análisis exploratorio

Me has descubierto esto: `msno.bar()` y `msno.matrix()`! No lo conocía y me parece una manera genial de explorar los nulos!

El análisis es bastante completo y nos da una idea global de los datos con los vamos a trabajar. 

Me faltaría que especifiques cuales son las hipótesis que vas a intentar comprobar antes de empezar con la limpieza. Pero por lo demás está super completo👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼👏🏼.

## Limpieza

La limpieza está suuper bien, has utilizado diccionarios para los replace lo cual atomiza muchísimo tu código ¡muy buena práctica!.

 Solo quedaría meter en funciones todo lo que puedas del código y pasarlas a un `archivo.py` para importarlas desde él y no tenerlas escritas en tu jupyter.

 Acuerdate de poner el docstring en todas las funciones para que se sepa lo que hacen. En la función especies, has dejado el docstring fuera y debería estar así:

```python
def species(x):
    '''Función para limpiar la columna de especie, el parámetro lo debo 
    convertir en string porque tiene elementos nan que interpreta como
    float. El retorno de búsqueda es un array por eso le paso la posición 0. 
    El .title pone la primera letra de la palabra en mayúscula.
    El return es np.nan para que directamente devuelva un valor
    nan y así los excluye en las visualizaciones'''
    
    busqueda = re.findall(pattern, str(x))
    try:
        return busqueda[0].title()
    except:
        return np.nan 
```
Por último cuando entregues un proyecto procura que no haya celdas vacías, ejecutadas con errores ni cosas así para dejar el jupyter lo más despejado posible.

## Visualización

La visualización está muy bien trabajada, has cuidado todos los detalles de color para que tenga una coherencia el jupyter completo y los gráficos están bien elegidos en función de lo que quieres mostrar.Sin embargo, en el último plot al estar super puestos los colores no se distinguen bien... quizá puedas cambiar alguno para que contraste un poco más.


# INTERPRETACIÓN Y CONCLUSIONES

Falta plantear hipótesis explícitamente y demostrarlas con la visualización. Cuando hagas visualización siempre siempre tiene que ir acompañada de una explicación por escrito.

Es importante que expliques lo que tu ves en el plot como si se lo estuvieras explicando a alguien que no entiende nada del proyecto, ten en cuenta que aunque para ti sea muy obvio lo que significan los plots, no todo el mundo tiene porque saber interpretar gráficos, parte de tu trabajo como analista será explicar esas conclusiones obtenidas de tu análisis.


Quitando que faltan las hipótesis has hecho uun buen trabajo de limpieza y visualización. Puliendo un par de detalles dejas el proyecto perfect!!!
:rocket::rocket::rocket::rocket::rocket::rocket::rocket:
