### ISSUE TITLE
[w3-pandas-project] Ricardo Sierra

### ISSUE THREAD

**Issue by Gitfracto** [Ironhack-Data-Madrid-Enero-2022/w3-pandas-project#5]
https://github.com/Gitfracto/data-cleaning-pandas.git

Proyecto terminado!

**Comment by Fominayasg** [comment]
# Buenas Ricardo!! :smile:

Vamos a ver qué tal ese proyecto!! 

Voy a echar un ojo a todo el proyecto y te dejaré por aquí mi feedback con lo que más me ha gustado y con cosillas a mejorar.

Aunque este mensaje te llegue al mail, podrás verlo mucho mejor directamente en la issue en github. 

# README

El comienzo engancha y da ganas de saber más de tu proyecto. Solo ten cuidado con que no quede raro lo de que los tiburones son "sexistas".  :laughing:
Falta el link a la página concreta de kaggle.

Cuando puedas dedica un ratillo a revisar erratas.

En cuanto al technology stack queda mejor si pones solo el nombre de las herramientas que usaste para hacer el proyecto linkadas a su documentación. Puedes escribirlo así:

```markdown
#### Technology Stack

- [Folium](https://python-visualization.github.io/folium/)
- [Pandas](https://pandas.pydata.org/docs/)
- [Geopandas](https://geopandas.org/)
- [Mongodb](https://www.mongodb.com/)
```
Para que se vea asi: 

#### Technology Stack

- [Folium](https://python-visualization.github.io/folium/)
- [Pandas](https://pandas.pydata.org/docs/)
- [Geopandas](https://geopandas.org/)
- [Mongodb](https://www.mongodb.com/)

---

El apartado "SRC folder", en vez de un apartado como tal, normalmente se incluye en "Repository structure" o algo así en el que digas qué hay en cada carpeta de tu repositorio.
# ESTRUCTURA DEL REPO
Las estructura del repo está super bien, sólo mejoraría un par de cosas.

1. Ya que tienes todo el repo en inglés, la carpeta imagen llámala images también no?? jeje
1. Los archivos csv mejor meterlos en una carpeta llamada data.
1. Si numeras tus jupyter, haces más fácil seguir el proyecto. En este caso concreto sólo hay dos y no es demasiado problemático pero es mejor irse acostumbrando de cara a proyectos más grandes. 


# CÓDIGO
## Análisis exploratorio

El análisis exploratorio como tal, no está. Lo único que veo es un `tiburon.info()`. Y luego directamente empiezas a limpiar el dataset.

Para que la limpieza esté más dirigida y podamos invertir nuestras energías de manera más eficiente, primero tenemos que saber con qué datos estamos trabajando.

Para ello será necesario ver qué dentro de nuestras columnas, ver si hay algunas parecidas(sé que más adelante lo comentas pero es ago que debemos hacer al principio), checkear sus valores únicos. Incluso podemos sacar algun gráfico sencillo de alguna columan que nos interese.

Una vez hecho esto, tendremos todas la herramientas en la mano para poder formular nuestras hipótesis y a paartir de ellas organizar la limpieza de datos.

## Limpieza

La limpieza general está bastante bien. En cuanto a la elección de las columnas a limpiar.
además tienes el jupyter bastante comentado (El Ricardo del futuro te lo agradecerá)

Te dejo algunos tips para dejarlo aún mejor:
`case_number_2`¿Podría haber servido para rellenar NaNs?? No se si lo has probado en algun momento pero cuando tenemos columnas con la misma información siempre es interesante checkearlo.

Por otro lado hay varios momentos en los que haces un `set`de un `.unique()`. Esto no es necesario ya que con el `.unique`ya obtienes los valores uúnicos ( a no ser que sea para dejarlos ordenados claro, en cuyo caso me parece una genialidad pero te sobra el `.unique`🤓).

#### Archivo de funciones
Lo primero de todo , genial que hayas logrado pasar las funciones a un .py e importarlas a jupyter para la limpieza, y en tu primer proyecto!!¡Enhorabuena!


## Visualización

Está muy muy bien, se nota que tienes buen manejo de gráficos y comprendes para que sirve cada uno y cuando usarlos. ¡Enhorabuena!

Solo te diría una cosa a mejorar. Tienes visualizaciones repetidas en el jupyter de limppieza y en el de visualización. Procura no repetir código, tómate la organización del proyecto como si lo fuera a leer alguien que no tiene ni idea ´8q ue es lo que va a pasar, resordemos que github es público)

# INTERPRETACIÓN Y CONCLUSIONES
Al final de este jupyter estaría genial que pongas un pequeño párrafo como conclusión. Es decir, tres o cuatro frases que resuman qué es lo que tu has sacado en claro del proyecto y de los datos.


En resumen, has hecho un muy buen proyecto Ricardo, enhorabuena!!
:rocket::rocket::rocket::rocket::rocket:
