### ISSUE TITLE
[w3-pandas-project] Eva Arquero

### ISSUE THREAD

**Issue by evaarquero** [Ironhack-Data-Madrid-Enero-2022/w3-pandas-project#8]
https://github.com/evaarquero/data-cleaning-pandas

**Comment by Fominayasg** [comment]
# Buenas Eva!! :smile:

Vamos a ver qué tal ese proyecto!! 

Voy a echar un ojo a todo el trabajo y te dejaré por aquí mi feedback con lo que más me ha gustado y con cosillas a mejorar.

Aunque este mensaje te llegue al mail, podrás verlo mucho mejor directamente en la issue en github. 

# README
Está super organizado y claro, lo cual se agradece mucho a la hora de leerlo  y dan ganas de seguir viendo el proyecto. Genial que hayas aprovechado el formato markdown para ello.

Al principio pones `se empieza con una base de datos de ataques de tiburones` . Sé que este proyecto se hizo en las primeras semanas, pero es importante distinguir entre base de datos y dataframe, porque si pones que un csv es una base de datos da la sensación de que no entiendes qué es una base de datos.

Las hipótesis están claras y muy accesibles (es lo primero que me llama la atención en el readme).

El cleaning está super bien descrito. Normalmente no hace falta especificar qué hemos hecho para limpiar nuestros datos, pero dado que este proyecto iba esencialmente de esto, está bien.

La sección `Hipótesis extras`, entiendo que son nuevas hipótesis que te han surgido al trabajar con los datos. ¡Buena idea!

Por último te falta la sección `Technology stack`con las librerías que hayas utilizado.

Para ello, te recomiendo que incluyas los links de está manera:

```markdown
In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
 
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[functions.py](https://github.com/evaarquero/data-cleaning-pandas/blob/main/src/functions.py)"
```

Y te quedaría asi:

In this project we have used the following libraries:
 - [pandas](https://pandas.pydata.org/docs/)
 
 - [numpy](https://numpy.org/doc/stable/)
 
 - [plotly](https://plotly.com/python/)
  
 - [seaborn](https://seaborn.pydata.org/)
 
 - our own "[functions.py](https://github.com/evaarquero/data-cleaning-pandas/blob/main/src/functions.py)"



# ESTRUCTURA DEL REPO

Está genial, lo único que añadiría es numerar los jupyters para saber en que orden habría que leerlos o ejecutarlos. 

Esto es un poco cuestión de gustos, pero a mi me parece que cuando alguien entra en un repo, cuanto más masticadita le demos la lecturar mejor.

En la carpeta src, al archivo de funciones lo has llamado `functions.py`... Por convención lo ideal es que el nombre describa lo que hay dentro de ese archivo. Por ejemplo: `cleaning_functions.py` o `visualizacion_functions.py`.

Por lo demás nada que decir... más ordenado imposible. Mi toc hace fiestas con tu repo.

# CÓDIGO
## Análisis exploratorio
Me falta esta parte del proyecto, para saber lo que tienes que limpiar y qué hay en tus datos, para después poder formular tus hipótesis tiene que haber un análisis exploratorio previo.

Ten en cuenta que en este caso es un tema que nos es familiar y podemos intentar sacar hipótesis incluso sin ver los datos, pero es una visión sesgada y podríamos estar pasando por alto cosas importantes.

Por lo menos ver los valores únicos que tenemos en las columnas, qué tipo de datos tenemos...etc.
## Limpieza

No veo ninguna función de limpieza en el código. Has hecho una carpeta src y un archivo de funciones pero no los has usado. Tienes varias lineas de código repetidas en el jupyter. Cuando esto nos ocurra automáticamente tenemos que pensar en modularizarlo en funciones.

Por ejemplo, en todos esos .replace() seguidos puedes utilizar un diccionario para reemplazar valores. [Aquí](https://stackoverflow.com/questions/14156473/can-you-write-a-str-replace-using-dictionary-values-in-python) te dejo un link a stackoverflow donde lo hacen.

O por ejemplo aquí:
```python
df.drop(df[df["Species"] == 'Shark involvement questionable'].index, inplace=True) 
df.drop(df[df["Species"] == 'Shark involvement prior to death was not confirmed'].index, inplace=True)
df.drop(df[df["Species"] == 'Invalid'].index, inplace=True)
df.drop(df[df["Species"] == 'Invalid'].index, inplace=True)
df.drop(df[df["Species"] == 'Shark involvement not confirmed'].index, inplace=True)
df.drop(df[df["Species"] == 'Questionable incident'].index, inplace=True)
df.drop(df[df["Species"] == 'Questionable'].index, inplace=True)
df.drop(df[df["Species"] == 'No shark involvement'].index, inplace=True)
df.drop(df[df["Species"] == 'Shark involvement prior to death not confirmed'].index, inplace=True)
df.drop(df[df["Species"] == 'Shark involvement suspected but not confirmed'].index, inplace=True)
df.drop(df[df["Species"] == 'Shark involvement questionable'].index, inplace=True)
df.drop(df[df["Species"] == 'Questionable Incident'].index, inplace=True)
df.drop(df[df["Species"] == 'Shark involvement not cofirmed'].index, inplace=True)
```
Mira a ver si lo puedes poner sin repetir código (por ejemplo poniendo que droppee las filas en las que tengas cualquiera de esas cosas, y las metes en una lista y luego las borras de la dataframe).

Por último me has mezclado la visualización con la limpieza. Tiene sentido tal y como lo haces, pero si separas jupyter de limpieza y jupyter de visualización lo suyo es que esté separado de verdad. Por otro lado ten en cuenta que de cara a empresa estas dos partes del proceso deben ir separadas, puede incluso que lo hagan personas diferentes.



## Visualización

La visualización está muy muy bien Eva, muy cuidada y bien explicada. 

Lo único es que en el plot de actividades las actividades minoritarias no se aprecian. Quizá con un eje y más grande se vea mejor.
Por lo demás poco que decir sobre esta parte. ¡Enhorabuena!

# RESUMEN

El proyecto cumple con los requisitos propuestos. Está bastante bien organizado y se nota que entiendes lo que estás haciendo. 

Como next steps puedes meter el codigo de limpieza en funciones para que tus jupyter queden más limpios y claros.

Buen trabajo Eva!!

**Comment by evaarquero** [comment]
Muchas gracias por los comentarios!  :smiley:
